services:
  mysql:
    image: mysql:8
    container_name: db_portofolio
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  backend: 
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://root:${DB_ROOT_PASSWORD}@mysql:3306/${DB_NAME}
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
    command: npm run dev
  
volumes:
  mysql_data:
